name: offline_map_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Core dependencies for offline functionality
  flutter_map: ^8.1.1
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  device_info_plus: ^9.1.1
  geojson_vi: ^2.2.5
  latlong2: ^0.9.0
  
  # Remove Firebase packages - they're not needed for offline functionality
  # cloud_firestore: ^4.13.6
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.15.3
  
  # Optional: In-app purchase for later
  in_app_purchase: ^3.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/basemaps/india_basemap.mbtiles
    - assets/layers/india_states.geojson
    # - assets/layers/india_rivers.geojson
